services:
  _defaults:
    autowire: true
    autoconfigure: true

  ICS\CronBundle\Controller\:
    resource: "../src/Controller"
    tags: ['controller.service_arguments']
  ICS\CronBundle\Command\:
    resource: "../src/Command"
    tags: ['controller.service_arguments']